version: '2'
services:
  myservice:
    image: owncloud:latest
    hostname: owncloud.example.org
    entrypoint: entrypoint.sh
    ports:
      - "3330-3333:5555-5558"
      - "2220-2221:3330-3331/udp"
    env_file:
      - ./extended.env
    environment:
      MYVAR1: MYVALFROMFILE_OVERWRITTEN_IN_ENVIRONMENT
      HTTP_HOST: myservice.example.org
      HTTP_PORT: 5550
