version: '2'
services:
  myservice:
    image: alpine:latest
    hostname: alpine
    #entrypoint: ["/bin/sh", "-c", "echo start; sleep 3; echo end"]
    #entrypoint: cat -
    tty: true
    #stdin_open: true
    ports:
      - "3330-3333:5555-5558"
      - "2220-2221:3330-3331/udp"
    env_file:
      - ./extended.env
    environment:
      MYVAR1: MYVALFROMFILE_OVERWRITTEN_IN_ENVIRONMENT
      HTTP_HOST: myservice.example.org
      HTTP_PORT: 5550
